# Generated by Django 6.0.6 on 2026-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название места')),
                ('region', models.CharField(max_length=100, verbose_name='Регион / область')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/photos/', verbose_name='Фото')),
                ('category', models.CharField(choices=[('bazaar', 'Базар'), ('nature', 'Природное место'), ('sight', 'Достопримечательность'), ('other', 'Другое')], max_length=50, verbose_name='Категория')),
            ],
        ),
    ]
