# Generated by Django 6.0.6 on 2026-06-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название места'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название места'),
        ),
        migrations.AddField(
            model_name='place',
            name='region_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Регион / область'),
        ),
        migrations.AddField(
            model_name='place',
            name='region_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Регион / область'),
        ),
    ]
