# Generated by Django 6.0.6 on 2026-06-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='app',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='app',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название приложения'),
        ),
        migrations.AddField(
            model_name='app',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название приложения'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название службы'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название службы'),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='username_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя аккаунта'),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='username_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя аккаунта'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название сервиса'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название сервиса'),
        ),
        migrations.AddField(
            model_name='traveltip',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='traveltip',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='traveltip',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Совет'),
        ),
        migrations.AddField(
            model_name='traveltip',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Совет'),
        ),
    ]
