# Generated by Django 6.0.6 on 2026-06-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('park', 'Парк'), ('museum', 'Музей'), ('mall', 'Торговый центр'), ('bazaar', 'Базар'), ('restaurant', 'Ресторан'), ('attraction', 'Достопримечательность')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bishkek/', verbose_name='Фотография')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('google_maps', models.URLField(blank=True, verbose_name='Google Maps')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
