# Generated by Django 6.0.6 on 2026-06-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishkek', '0002_alter_place_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BishkekIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bishkek/photos/', verbose_name='Фото')),
            ],
        ),
    ]
