# Generated by Django 6.0.6 on 2026-06-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='history/audio/', verbose_name='Аудио'),
        ),
    ]
