# Generated by Django 6.0.6 on 2026-06-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_culture_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='audio_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст к аудио'),
        ),
    ]
