# Generated by Django 6.0.6 on 2026-06-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_culture_audio_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube'),
        ),
    ]
