# Generated by Django 6.0.6 on 2026-06-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_cultureimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoch',
            name='name',
            field=models.CharField(max_length=2000, verbose_name='Эпоха'),
        ),
    ]
