# Generated by Django 6.0.6 on 2026-06-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='language',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='language',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='musicalinstrument',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='musicalinstrument',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='musicalinstrument',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Музыкальный инструмент'),
        ),
        migrations.AddField(
            model_name='musicalinstrument',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Музыкальный инструмент'),
        ),
        migrations.AddField(
            model_name='nationalgame',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='nationalgame',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='nationalgame',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Национальная игра'),
        ),
        migrations.AddField(
            model_name='nationalgame',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Национальная игра'),
        ),
        migrations.AddField(
            model_name='people',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание о народе'),
        ),
        migrations.AddField(
            model_name='people',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание о народе'),
        ),
        migrations.AddField(
            model_name='population',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='population',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='population',
            name='number_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Население'),
        ),
        migrations.AddField(
            model_name='population',
            name='number_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Население'),
        ),
    ]
