# Generated by Django 6.0.6 on 2026-06-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Статья / описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='nature/photos/', verbose_name='Фото')),
            ],
        ),
    ]
