# Generated by Django 6.0.6 on 2026-06-18 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('main_description', models.TextField(verbose_name='Общее описание')),
            ],
        ),
        migrations.CreateModel(
            name='NatureContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='nature/photos/', verbose_name='Фото')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='nature.naturearticle')),
            ],
        ),
        migrations.DeleteModel(
            name='Nature',
        ),
    ]
