# Generated by Django 6.0.6 on 2026-06-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0002_naturearticle_naturecontent_delete_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturearticle',
            name='main_description_en',
            field=models.TextField(null=True, verbose_name='Общее описание'),
        ),
        migrations.AddField(
            model_name='naturearticle',
            name='main_description_ru',
            field=models.TextField(null=True, verbose_name='Общее описание'),
        ),
        migrations.AddField(
            model_name='naturearticle',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='naturearticle',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='naturecontent',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='naturecontent',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
