# Generated by Django 6.0.6 on 2026-06-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('main', 'Основные блюда'), ('flour', 'Мучное'), ('delicacy', 'Деликатесы'), ('dessert', 'Лакомства'), ('drink', 'Напитки')], default=1, max_length=20, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food/photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
