# Generated by Django 6.0.6 on 2026-06-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_category_alter_food_image_alter_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='drink',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='drink',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название напитка'),
        ),
        migrations.AddField(
            model_name='drink',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название напитка'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
